// قائمة الجنسيات (رمز ISO + الاسم العربي والإنجليزي). العلم يُشتق من الرمز.
// مستبعدة: إسرائيل (IL). الجنسيات المثبّتة أولاً: السعودية، سوريا، الفلبين، باكستان، مصر.

export function codeToFlag(code) {
  if (!code || code.length !== 2) return '';
  const cc = code.toUpperCase();
  if (!/^[A-Z]{2}$/.test(cc)) return '';
  return String.fromCodePoint(...[...cc].map((c) => 127397 + c.charCodeAt(0)));
}

export const PINNED_CODES = ['SA', 'SY', 'PH', 'PK', 'EG'];

const RAW = [
  ['SA', 'سعودية', 'Saudi Arabia'],
  ['SY', 'سورية', 'Syria'],
  ['PH', 'فلبينية', 'Philippines'],
  ['PK', 'باكستانية', 'Pakistan'],
  ['EG', 'مصرية', 'Egypt'],
  ['AE', 'إماراتية', 'United Arab Emirates'],
  ['BH', 'بحرينية', 'Bahrain'],
  ['KW', 'كويتية', 'Kuwait'],
  ['OM', 'عُمانية', 'Oman'],
  ['QA', 'قطرية', 'Qatar'],
  ['YE', 'يمنية', 'Yemen'],
  ['JO', 'أردنية', 'Jordan'],
  ['LB', 'لبنانية', 'Lebanon'],
  ['IQ', 'عراقية', 'Iraq'],
  ['PS', 'فلسطينية', 'Palestine'],
  ['SD', 'سودانية', 'Sudan'],
  ['LY', 'ليبية', 'Libya'],
  ['TN', 'تونسية', 'Tunisia'],
  ['DZ', 'جزائرية', 'Algeria'],
  ['MA', 'مغربية', 'Morocco'],
  ['MR', 'موريتانية', 'Mauritania'],
  ['SO', 'صومالية', 'Somalia'],
  ['DJ', 'جيبوتية', 'Djibouti'],
  ['KM', 'قمرية', 'Comoros'],
  ['IN', 'هندية', 'India'],
  ['BD', 'بنغلاديشية', 'Bangladesh'],
  ['LK', 'سريلانكية', 'Sri Lanka'],
  ['NP', 'نيبالية', 'Nepal'],
  ['ID', 'إندونيسية', 'Indonesia'],
  ['MY', 'ماليزية', 'Malaysia'],
  ['AF', 'أفغانية', 'Afghanistan'],
  ['IR', 'إيرانية', 'Iran'],
  ['TR', 'تركية', 'Turkey'],
  ['CN', 'صينية', 'China'],
  ['JP', 'يابانية', 'Japan'],
  ['KR', 'كورية جنوبية', 'South Korea'],
  ['TH', 'تايلندية', 'Thailand'],
  ['VN', 'فيتنامية', 'Vietnam'],
  ['MM', 'ميانمارية', 'Myanmar'],
  ['KH', 'كمبودية', 'Cambodia'],
  ['LA', 'لاوسية', 'Laos'],
  ['SG', 'سنغافورية', 'Singapore'],
  ['MV', 'مالديفية', 'Maldives'],
  ['BT', 'بوتانية', 'Bhutan'],
  ['KZ', 'كازاخستانية', 'Kazakhstan'],
  ['UZ', 'أوزبكية', 'Uzbekistan'],
  ['TM', 'تركمانية', 'Turkmenistan'],
  ['TJ', 'طاجيكية', 'Tajikistan'],
  ['KG', 'قرغيزية', 'Kyrgyzstan'],
  ['AZ', 'أذربيجانية', 'Azerbaijan'],
  ['AM', 'أرمينية', 'Armenia'],
  ['GE', 'جورجية', 'Georgia'],
  ['NG', 'نيجيرية', 'Nigeria'],
  ['GH', 'غانية', 'Ghana'],
  ['ET', 'إثيوبية', 'Ethiopia'],
  ['ER', 'إريترية', 'Eritrea'],
  ['KE', 'كينية', 'Kenya'],
  ['UG', 'أوغندية', 'Uganda'],
  ['TZ', 'تنزانية', 'Tanzania'],
  ['SS', 'جنوب سودانية', 'South Sudan'],
  ['CM', 'كاميرونية', 'Cameroon'],
  ['SN', 'سنغالية', 'Senegal'],
  ['ML', 'مالية', 'Mali'],
  ['NE', 'نيجرية', 'Niger'],
  ['TD', 'تشادية', 'Chad'],
  ['BF', 'بوركينية', 'Burkina Faso'],
  ['CI', 'إيفوارية', "Côte d'Ivoire"],
  ['GN', 'غينية', 'Guinea'],
  ['BJ', 'بنينية', 'Benin'],
  ['TG', 'توغولية', 'Togo'],
  ['SL', 'سيراليونية', 'Sierra Leone'],
  ['LR', 'ليبيرية', 'Liberia'],
  ['GM', 'غامبية', 'Gambia'],
  ['ZA', 'جنوب أفريقية', 'South Africa'],
  ['ZW', 'زيمبابوية', 'Zimbabwe'],
  ['ZM', 'زامبية', 'Zambia'],
  ['MW', 'مالاوية', 'Malawi'],
  ['MZ', 'موزمبيقية', 'Mozambique'],
  ['AO', 'أنغولية', 'Angola'],
  ['RW', 'رواندية', 'Rwanda'],
  ['BI', 'بوروندية', 'Burundi'],
  ['CD', 'كونغولية (الديمقراطية)', 'DR Congo'],
  ['CG', 'كونغولية', 'Congo'],
  ['GA', 'غابونية', 'Gabon'],
  ['MG', 'مدغشقرية', 'Madagascar'],
  ['MU', 'موريشيوسية', 'Mauritius'],
  ['SC', 'سيشيلية', 'Seychelles'],
  ['GB', 'بريطانية', 'United Kingdom'],
  ['IE', 'أيرلندية', 'Ireland'],
  ['FR', 'فرنسية', 'France'],
  ['DE', 'ألمانية', 'Germany'],
  ['IT', 'إيطالية', 'Italy'],
  ['ES', 'إسبانية', 'Spain'],
  ['PT', 'برتغالية', 'Portugal'],
  ['NL', 'هولندية', 'Netherlands'],
  ['BE', 'بلجيكية', 'Belgium'],
  ['CH', 'سويسرية', 'Switzerland'],
  ['AT', 'نمساوية', 'Austria'],
  ['SE', 'سويدية', 'Sweden'],
  ['NO', 'نرويجية', 'Norway'],
  ['DK', 'دنماركية', 'Denmark'],
  ['FI', 'فنلندية', 'Finland'],
  ['IS', 'آيسلندية', 'Iceland'],
  ['PL', 'بولندية', 'Poland'],
  ['CZ', 'تشيكية', 'Czechia'],
  ['SK', 'سلوفاكية', 'Slovakia'],
  ['HU', 'مجرية', 'Hungary'],
  ['RO', 'رومانية', 'Romania'],
  ['BG', 'بلغارية', 'Bulgaria'],
  ['GR', 'يونانية', 'Greece'],
  ['HR', 'كرواتية', 'Croatia'],
  ['RS', 'صربية', 'Serbia'],
  ['BA', 'بوسنية', 'Bosnia and Herzegovina'],
  ['SI', 'سلوفينية', 'Slovenia'],
  ['MK', 'مقدونية', 'North Macedonia'],
  ['AL', 'ألبانية', 'Albania'],
  ['ME', 'جبل أسود', 'Montenegro'],
  ['XK', 'كوسوفية', 'Kosovo'],
  ['UA', 'أوكرانية', 'Ukraine'],
  ['BY', 'بيلاروسية', 'Belarus'],
  ['RU', 'روسية', 'Russia'],
  ['MD', 'مولدوفية', 'Moldova'],
  ['LT', 'ليتوانية', 'Lithuania'],
  ['LV', 'لاتفية', 'Latvia'],
  ['EE', 'إستونية', 'Estonia'],
  ['CY', 'قبرصية', 'Cyprus'],
  ['MT', 'مالطية', 'Malta'],
  ['LU', 'لوكسمبورغية', 'Luxembourg'],
  ['US', 'أمريكية', 'United States'],
  ['CA', 'كندية', 'Canada'],
  ['MX', 'مكسيكية', 'Mexico'],
  ['BR', 'برازيلية', 'Brazil'],
  ['AR', 'أرجنتينية', 'Argentina'],
  ['CL', 'تشيلية', 'Chile'],
  ['CO', 'كولومبية', 'Colombia'],
  ['PE', 'بيروفية', 'Peru'],
  ['VE', 'فنزويلية', 'Venezuela'],
  ['EC', 'إكوادورية', 'Ecuador'],
  ['BO', 'بوليفية', 'Bolivia'],
  ['PY', 'باراغوانية', 'Paraguay'],
  ['UY', 'أوروغوانية', 'Uruguay'],
  ['CU', 'كوبية', 'Cuba'],
  ['DO', 'دومينيكية', 'Dominican Republic'],
  ['HT', 'هايتية', 'Haiti'],
  ['JM', 'جامايكية', 'Jamaica'],
  ['GT', 'غواتيمالية', 'Guatemala'],
  ['HN', 'هندوراسية', 'Honduras'],
  ['SV', 'سلفادورية', 'El Salvador'],
  ['NI', 'نيكاراغوية', 'Nicaragua'],
  ['CR', 'كوستاريكية', 'Costa Rica'],
  ['PA', 'بنمية', 'Panama'],
  ['AU', 'أسترالية', 'Australia'],
  ['NZ', 'نيوزيلندية', 'New Zealand'],
  ['FJ', 'فيجية', 'Fiji'],
  ['PG', 'بابوية', 'Papua New Guinea'],
];

export const COUNTRIES = RAW.map(([code, ar, en]) => ({ code, ar, en, flag: codeToFlag(code) }));

const BY_CODE = Object.fromEntries(COUNTRIES.map((c) => [c.code, c]));

export function countryByCode(code) {
  return code ? BY_CODE[code] || null : null;
}

// مرتّبة: المثبّتة أولاً بترتيبها، ثم البقية أبجدياً بالعربية
export const COUNTRIES_SORTED = [
  ...PINNED_CODES.map((c) => BY_CODE[c]).filter(Boolean),
  ...COUNTRIES.filter((c) => !PINNED_CODES.includes(c.code)).sort((a, b) => a.ar.localeCompare(b.ar, 'ar')),
];
